FROM microsoft/aspnetcore-build:1.1

COPY . ./app
WORKDIR /app

RUN ["dotnet", "restore"]
RUN ["dotnet", "build"]

RUN dotnet publish -c Debug -o build

FROM microsoft/aspnetcore:1.1

WORKDIR /app

COPY ./src/Presentation.API/build .
EXPOSE 80

ENTRYPOINT ["dotnet", "Presentation.API.dll"]
