#%RAML 1.0
title: feature-toggle-api
version: v1
baseUri: http://api.feature-toggle.com
types:
  TestType:
    type: object
    properties:
      id: number
      optional?: string
      expanded:
        type: object
        properties:
          count: number
/toggle-goups:
  description: Create and define a group that a toggle may belong.
  post:
    description: Create a toggle-group
    body:
      application/json:
        example: |
          {
            "name": "UI",
            "description": "Group for UI toggles",
            "tags": ["UI", "buttons", "views", "frameworks", "js"]
          }
  get:
    description:
    responses:
      200:
        description: Return all toggle groups with respective descriptions
        body:
          application/json:
            example: |
              [
                {
                  "id": "5908a2e017293d1ae07322ed"
                  "name": "UI",
                  "description": "Group for UI toggles",
                  "tags": ["UI", "buttons", "views", "frameworks", "js"],
                  "created": "2017-05-06"
                },
                {
                  "id": "5908a2e017293d1ae03232ed"
                  "name": "Feature",
                  "description": "Group for Feature toggles",
                  "tags": ["Feature", "application", "functionality"],
                  "created": "2017-05-06"
                }
              ]
      500:
        body:
         application/json:
           example: |
             {
               "errorCode": 500,
               "message": "Internal Server Error."
             }
  /{id}:
    description:
    get:
      description:
      responses:
        200:
        400:
        403:
        404:
        500:
    /toggles:
     description:
     get:
      description:
      responses:
        200:
        400:
        403:
        404:
        500:
      queryParameters:
        date:
          displayName: date
          type: string
          description: filter toggles by date
          example: 2017-05-05
          required: false
        tag:
          displayName: tag
          type: string
          description: filter toggles by tag
          required: false
          example: buttons
        name:
          displayName: name
          type: string
          description: filter toggles by name
          required: false
          example: EnableRedButtons
        id:
          displayName: id
          type: string
          description: filter toggles by id
          required: false
          example: 5908a2e017293d1ae07322ed
/queue/{id}:
  get:
    description:
    responses:
      200:
        description:
        body:
          application/json:
            example: |
              {
                status: "In progress"
              }
      303:
        description: The 303 code implies that there is another resource that must be fetched instead of this resource.
        body:
          application/json:
            example: |
              {
                location: "/toggles/1"
              }
/toggles:
  description:
  post:
    description: The location URI points to a (created) resource that will display the status of the asynchronous processing.
    responses:
      202:
        body:
          application/json:
            example: |
              {
                location: "/toggles/1"
              }
      400:
        body:
         application/json:
           example: |
             {
               "errorCode": 400,
               "message": "Bad Request."
             }
      422:
        body:
         application/json:
           example: |
             {
               "errorCode": 422,
               "message": "The entity is invalid."
             }
  get:
    description:
    responses:
      200:
        body:
          application/json:
            example: |
              [
                {
                  "EnableRedButtons": true
                },
                {
                  "EnableKafkaProducer": false
                }
              ]
      400:
        body:
         application/json:
           example: |
             {
               "errorCode": 400,
               "message": "Bad Request."
             }
      404:
        body:
         application/json:
           example: |
             {
               "errorCode": 404,
               "message": "Entity Not Found."
             }
      500:
        body:
         application/json:
           example: |
             {
               "errorCode": 500,
               "message": "Internal Server Error."
             }
    queryParameters:
  /{id}:
    description:
    get:
      description:
      responses:
        200:
        400:
        403:
        404:
        500:
      queryParameters:
    delete:
      description:
      responses:
    patch:
      description:
      responses:
    /toggle-groups:
      description:
      get:
        description:
        responses:
          200:
          400:
          403:
          404:
          500:
        queryParameters:
  /{tag}:
    description:
    get:
      description:
      responses:
        200:
        400:
        403:
        404:
        500:
      queryParameters:
