FROM microsoft/aspnetcore-build AS build-env
WORKDIR /feature-toggle-map

COPY /src/* ./build/
COPY /test/* ./build/
WORKDIR /feature-toggle-map
RUN dotnet restore
# RUN dotnet restore ./test

COPY . .
RUN dotnet publish --output /out/ -c Release

# command to build the image
# docker build -f Dockerfile.build -t ftm-test-build .

# command to create the image
# docker create --name ftm-test-build-container ftm-test-build
